apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- cluster-issuer.yaml
- api/deployment.yaml
- api/service.yaml
- api/hpa.yaml
- frontend/deployment.yaml
- frontend/service.yaml
- ingress.yaml

images:
- name: url-lengthener-api
  newName: 235336959928.dkr.ecr.eu-west-1.amazonaws.com/url-lengthener-api
  newTag: f6bf2f86bf7223c796bcfa6dd8330c4a4f611c5c
- name: url-lengthener-frontend
  newName: 235336959928.dkr.ecr.eu-west-1.amazonaws.com/url-lengthener-frontend
  newTag: 5839180f71df38a5db668eb5df1ea5f971fc8471
