root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server/main.go"
  bin = "./tmp/server"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  include_dir = ["cmd", "internal"]

[screen]
  clear_on_rebuild = false
